# Generated by Django 5.2.6 on 2025-10-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hotel_created_at_hotel_image_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
