# Generated by Django 5.2.6 on 2025-10-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_roomimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
