# Generated by Django 5.2.6 on 2025-10-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_hotel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
