# Generated by Django 5.2.6 on 2025-10-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_hotel_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
