# Generated by Django 5.2.6 on 2025-10-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='distance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
