# Generated by Django 5.2.6 on 2025-10-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_hotel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimage',
            name='is_primary',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
