# Generated by Django 5.2.6 on 2025-10-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_roomavailability'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user',), name='one_booking_per_user'),
        ),
    ]
